export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $inputMask: document.getElementsByTagName('input[type="tel"]'),
  $header: document.querySelector('.js-header'),
  $worksSlider: document.querySelector('.works-slider'),
  $ahchorLinks: document.querySelectorAll('.js-anchor'),
  $modal: document.querySelector('.js-modal'),
  $modalOverlay: document.querySelector('.js-modal-overlay'),
  $openModalBtns: document.querySelectorAll('.js-open-modal'),
  $modalInputArea: document.querySelectorAll('.js-modal-input'),
  $closeModalBtn: document.querySelector('.js-modal-close'),
  $cancelFormBtn: document.querySelector('.js-form-cancel'),
  $toggleNavBtn: document.querySelector('.js-nav-btn'),
}
